services:

  turso:
    image: ghcr.io/tursodatabase/libsql-server:latest
    container_name: tentacloid-turso
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./data/libsql:/var/lib/sqld
    networks:
      - app_network

  dz-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: tentacloid-dz-gateway
    environment:
      STORE_PATH: /app
    restart: on-failure
    ports:
      - "4983:4983"
    volumes:
      - drizzle-gateway-data:/app
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:4.1.5-management-alpine
    container_name: tentacloid-queue
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/

networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq-lib:
  rabbitmq-log:
  drizzle-gateway-data:
